package reflection_database.model;

/**
 * Represents a customer with an ID, name, address, email, and age.
 */
public class Customer {
    private int id;
    private String name;
    private String address;
    private String email;
    private int age;

    /**
     * Constructs a Customer with all fields including the ID.
     *
     * @param id the unique identifier of the customer
     * @param name the name of the customer
     * @param address the address of the customer
     * @param email the email of the customer
     * @param age the age of the customer
     */
    public Customer(int id, String name, String address, String email, int age) {
        super();
        this.id = id;
        this.name = name;
        this.address = address;
        this.email = email;
        this.age = age;
    }
    /**
     * Default constructor for Customer.
     * Initializes a Customer with default values.
     */
    public Customer() {
    }
    /**
     * Constructs a Customer without an ID.
     * ID is generated by the database
     * @param name the name of the customer
     * @param address the address of the customer
     * @param email the email of the customer
     * @param age the age of the customer
     */
    public Customer(String name, String address, String email, int age) {
        super();
        this.name = name;
        this.address = address;
        this.email = email;
        this.age = age;
    }

    /**
     *Setters and getters
     */

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
    @Override
    public String toString() {
        return "Customer [id=" + id + ", name=" + name + ", address=" + address + ", email=" + email;
    }
}
