package reflection_database.model;

/**
 * Represents a product with an ID, product name, quantity in stock, price per unit, and kilograms per unit.
 */
public class Product {
    private int id;
    private String name;
    private int quantity;
    private int price_per_unit;
    private double kilos_per_unit;

    /**
     * Constructs a Customer with all fields including the ID.
     *
     * @param id the unique identifier of the product
     * @param name the name of the product
     * @param quantity the number of product units in stock
     * @param pricePerUnit the price for a single unit of product
     * @param kilosPerUnit the weight in kilos of a single unit of product
     */
    public Product(int id, String name, int quantity, int pricePerUnit, double kilosPerUnit) {
        this.id = id;
        this.name = name;
        this.quantity = quantity;
        this.price_per_unit = pricePerUnit;
        this.kilos_per_unit = kilosPerUnit;
    }
    /**
     * Constructs a Product without an ID.
     * ID is generated by the database
     * @param name the name of the product
     * @param quantity the number of product units in stock
     * @param pricePerUnit the price for a single unit of product
     * @param kilosPerUnit the weight in kilos of a single unit of product
     */
    public Product(String name, int quantity, int pricePerUnit, double kilosPerUnit) {
        this.name = name;
        this.quantity = quantity;
        this.price_per_unit = pricePerUnit;
        this.kilos_per_unit = kilosPerUnit;
    }

    public Product(){
    }
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public int getPrice_per_unit() {
        return price_per_unit;
    }

    public void setPrice_per_unit(int price_per_unit) {
        this.price_per_unit = price_per_unit;
    }

    public double getKilos_per_unit() {
        return kilos_per_unit;
    }

    public void setKilos_per_unit(double kilos_per_unit) {
        this.kilos_per_unit = kilos_per_unit;
    }
}